# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [1]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [4]:
#todo: 
array = np.array([1,2,3,4,5,6,7,8,9])
print(array)

[1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [14]:
#todo:
array = np.array([0,0,0,0,0])
print(f"""Array por defecto: {array}""")
array[2] = 5
print(f"""Array con el indice "2" reemplazado {array}""")

Array por defecto: [0 0 0 0 0]
Array con el indice "2" reemplazado [0 0 5 0 0]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [53]:
#todo: 
array_matriz = np.random.randint(low=0,high=2,size=(3,3))
print(array_matriz)

[[1 0 0]
 [0 1 0]
 [1 0 1]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [69]:
#todo:
arr = np.array([10, 20, 30, 40, 50])
print(f"""Array por defecto: {arr}""")
#Suma 5 a cada elemento del array
arr += 5
print(f"""Array + "5": {arr}""")

#Genera un numero ramdom entre {1 y 10} y multiplica a array por ese numero
multi = randint(1,10)
arr *= multi

print(f"""Numero que multiplica al array: {multi}""")
print(f"""Array multiplicado: {arr}""")

Array por defecto: [10 20 30 40 50]
Array + "5": [15 25 35 45 55]
Numero que multiplica al array: 4
Array multiplicado: [ 60 100 140 180 220]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#todo:
array = np.array([[1, 0, 0,0], [0, 1, 0,0], [0, 0, 1,0], [0, 0, 0,1]])
print(array)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [ ]:
#todo: 
#Crea un array con valores dentro del intervalo {0,21} 
# y los saltea cada 2 para generar solo numeros pares.
array = np.arange(0,21,2)

print(f"""Array por defecto: {array}""")
print(f"""Array + "4": {array + 4}""")
print(f"""Array - "4": {array - 4}""")
print(f"""Array * "4": {array * 4}""")
print(f"""Array / "4": {array / 4}""")



Array por defecto: [ 0  2  4  6  8 10 12 14 16 18 20]
Array + "4": [ 4  6  8 10 12 14 16 18 20 22 24]
Array - "4": [-4 -2  0  2  4  6  8 10 12 14 16]
Array * "4": [ 0  8 16 24 32 40 48 56 64 72 80]
Array / "4": [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
